name: Tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Environment Variables
        run: echo Setting insecure shit
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true
      - uses: actions/checkout@v2
      - name: nodenv/node-version
        uses: nodenv/actions-node-version@v2.0.7
        id: nodenv
      - uses: actions/setup-node@v1
        with:
          node-version: '${{ steps.nodenv.outputs.node-version }}'
      - run: yarn --frozen-lockfile
      - run: yarn test:ci
        env:
          CI: true
